[GLOBAL]
pants_version = "2.28.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.experimental.adhoc",
]

[system-binaries]
system_binary_paths = [
  "/usr/bin",
  "/bin",
  "/usr/local/bin",
  "/opt/homebrew/bin",
  "/home/*/.nvm/versions/node/*/bin",
  "/Users/*/.nvm/versions/node/*/bin",
]

[cli.alias]
all = "::"
lock = "generate-lockfiles"
venv = "export --py-resolve-format=symlinked_immutable_virtualenv --resolve=python-default"
demo = ":demo"
test-debug = "--test-debug test --pytest-args='--headed'"

[source]
root_patterns = ["/", "src/"]

[test]
use_coverage = true

[python]
interpreter_constraints = [">=3.11.0"]
enable_resolves = true

[ruff]
version = "0.11.0"
