package_json(
    name="monaco-editor-enhanced",
    scripts=[
        node_build_script(
            entry_point="build",
            output_files=["monaco-editor-enhanced-*.tgz"],
        ),
    ],
    dependencies=["src/react/monaco-editor-enhanced:tsx", "//:tsconfig"]
)
