name: Publish React Component

on:
  push:
    branches:
      - main
    paths:
      - "src/react/**"
  workflow_dispatch:

env:
  PANTS_CONFIG_FILES: pants.ci.toml

jobs:
  build:
    name: Release React Component
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Configure Pants caching to GitHub Actions Cache
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('PANTS_REMOTE_STORE_ADDRESS', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('PANTS_REMOTE_OAUTH_BEARER_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: Pants Package
      id: pants-package
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
        pants package react
        echo "version=v$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' src/react/package.json)" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2.2.2
      with:
        files: dist/src.react/build/monaco-editor-enhanced-*
        name: ${{ steps.pants-package.outputs.version }}+react
        tag_name: ${{ steps.pants-package.outputs.version }}+react
        fail_on_unmatched_files: true
        generate_release_notes: true
        make_latest: true
